# Generated by Django 4.1.10 on 2023-09-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_title',
            field=models.TextField(),
        ),
    ]
